//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jb_tools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailMenus
    {
        public int Id { get; set; }
        public int SortNum { get; set; }
        public string MainCode { get; set; }
        public string ScId { get; set; }
        public string DetailOrder { get; set; }
        public string Program { get; set; }
        public string Name { get; set; }
        public string Ename { get; set; }
        public string ProgramPath { get; set; }
        public string PosOrPath2 { get; set; }
        public string Remark { get; set; }
    }
}
