//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jb_tools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iecusuh
    {
        public int Id { get; set; }
        public string cu_no { get; set; }
        public string cu_sale { get; set; }
        public string cu_na { get; set; }
        public string cu_unit { get; set; }
        public string cu_type { get; set; }
        public string cu_taxno { get; set; }
        public string cu_boss { get; set; }
        public string cu_touch { get; set; }
        public decimal cu_disc { get; set; }
        public decimal cu_tax { get; set; }
        public decimal cu_check { get; set; }
        public string cu_date { get; set; }
        public decimal cu_crdt { get; set; }
        public string cu_sdat { get; set; }
        public decimal cu_ck { get; set; }
        public decimal cu_ar { get; set; }
        public string cu_area { get; set; }
        public string cu_chdat { get; set; }
        public string cu_bdat { get; set; }
        public decimal cu_invst { get; set; }
        public string cu_poar { get; set; }
        public string cu_ivar { get; set; }
        public string cu_charg { get; set; }
        public string cu_taxid { get; set; }
        public string cu_rela { get; set; }
        public string cu_crbi { get; set; }
        public decimal cu_pre { get; set; }
        public decimal cu_pr_lc { get; set; }
        public decimal cu_odamt { get; set; }
        public decimal cu_saamt { get; set; }
        public string bk_no { get; set; }
        public string ck_acno { get; set; }
        public string cu_id { get; set; }
        public string cu_zip { get; set; }
        public string cu_condi { get; set; }
        public string ie_ymd { get; set; }
        public string od_id { get; set; }
        public string cu_odid { get; set; }
        public string edi_code { get; set; }
        public string sa_route { get; set; }
        public string dps_co { get; set; }
        public string ck_acna { get; set; }
        public string cu_poar1 { get; set; }
        public string cu_ivar1 { get; set; }
        public string cu_email { get; set; }
        public string cu_ctid { get; set; }
        public string cu_stid { get; set; }
        public string cu_bkid { get; set; }
        public string cu_shid { get; set; }
        public string cu_cpid { get; set; }
        public string cu_paid { get; set; }
        public string cu_waid { get; set; }
        public string cu_otid { get; set; }
        public string cu_sid { get; set; }
        public string cu_pay { get; set; }
        public string cu_incmel { get; set; }
        public decimal lo_lim { get; set; }
        public decimal lo_amt { get; set; }
        public string bk_swift { get; set; }
        public decimal lo_ramt { get; set; }
        public string lo_id { get; set; }
        public decimal lo_lim1 { get; set; }
        public decimal bk_access { get; set; }
        public string wa_apli { get; set; }
        public string wa_tunit { get; set; }
        public string wa_tunit1 { get; set; }
        public string wa_febu { get; set; }
        public string wa_comtax { get; set; }
        public string tr_no { get; set; }
        public string ie_time { get; set; }
        public string ie_user { get; set; }
        public string ie_lymd { get; set; }
        public string ie_ltime { get; set; }
        public string ie_luser { get; set; }
        public string ie_cymd { get; set; }
        public string ie_ctime { get; set; }
        public string ie_cuser { get; set; }
        public decimal iv_page { get; set; }
        public string cu_cr { get; set; }
        public string cu_iv { get; set; }
        public string cu_ipd { get; set; }
        public string cu_gId { get; set; }
        public string wa_gui { get; set; }
        public string cu_lamtnol { get; set; }
        public string cu_lamtnoh { get; set; }
        public string cu_kamtno { get; set; }
        public string cu_kamtlno { get; set; }
        public string cu_kamtboss { get; set; }
        public string ie_cancel { get; set; }
        public string cu_name { get; set; }
        public string cu_ename { get; set; }
        public string cu_bil { get; set; }
        public decimal cu_de_check { get; set; }
        public string cu_ch { get; set; }
        public decimal cu_workhur { get; set; }
        public string ie_doc { get; set; }
        public string ie_odid { get; set; }
        public string cu_billar { get; set; }
        public string cu_headquar { get; set; }
        public string cu_billowner { get; set; }
        public string cu_ldat { get; set; }
        public string cu_addr { get; set; }
        public string ie_cser { get; set; }
        public string cu_taxyn { get; set; }
        public string cu_incono { get; set; }
        public string cu_noti { get; set; }
        public string cu_charg1 { get; set; }
        public string cu_agent { get; set; }
        public decimal cu_cashrt { get; set; }
        public string cu_cashyn { get; set; }
        public string cu_checkyn { get; set; }
        public decimal cu_discrt { get; set; }
        public string cu_discyn { get; set; }
        public string cu_pass { get; set; }
        public string ip_position { get; set; }
        public string sa_pryn { get; set; }
        public string cu_ctrsort { get; set; }
        public string cu_cuno { get; set; }
        public decimal cu_lead { get; set; }
        public string cu_no1 { get; set; }
        public decimal cu_rtax { get; set; }
        public string cu_send { get; set; }
        public string cu_stodid { get; set; }
        public decimal el_give { get; set; }
        public decimal el_mass { get; set; }
        public string cu_code { get; set; }
        public decimal ie_rtax { get; set; }
        public string ie_pass { get; set; }
        public string ie_past { get; set; }
        public string cu_nati { get; set; }
        public string cu_acname { get; set; }
        public string cu_scode { get; set; }
        public string cu_tm { get; set; }
        public string cu_city { get; set; }
        public string su_iv { get; set; }
        public string cu_ftype { get; set; }
        public string cu_barea { get; set; }
        public string cu_utype { get; set; }
        public string cu_source { get; set; }
        public string cu_stock { get; set; }
        public string cu_sale1 { get; set; }
        public string id_no { get; set; }
        public string tel_e { get; set; }
        public string tel_n { get; set; }
        public string tel_z { get; set; }
        public string cu_agid { get; set; }
        public string cu_brok { get; set; }
        public string cu_chno { get; set; }
        public string cu_property { get; set; }
        public string cu_hqid { get; set; }
        public string cu_stack { get; set; }
    }
}
