//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jb_tools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IemuTrans
    {
        public int Id { get; set; }
        public string No { get; set; }
        public string Status { get; set; }
        public string CuNo { get; set; }
        public string CuNa { get; set; }
        public string CuName { get; set; }
        public string CuEname { get; set; }
        public string CuSale { get; set; }
        public string CusaleName { get; set; }
        public string IndustryNo { get; set; }
        public string IndustryName { get; set; }
        public string Remark { get; set; }
    }
}
