//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jb_tools.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iepb03h
    {
        public int Id { get; set; }
        public string cu_sale { get; set; }
        public string cu_snam { get; set; }
        public string cu_snam1 { get; set; }
        public string cu_tel { get; set; }
        public string cu_handtel { get; set; }
        public string cu_email { get; set; }
        public string dp_no { get; set; }
        public string ie_pass { get; set; }
        public string cu_pass { get; set; }
        public string ie_ymd { get; set; }
        public string ie_time { get; set; }
        public string ie_user { get; set; }
        public string ie_lymd { get; set; }
        public string ie_ltime { get; set; }
        public string ie_luser { get; set; }
        public string ie_cymd { get; set; }
        public string ie_ctime { get; set; }
        public string ie_cuser { get; set; }
        public string ie_past { get; set; }
        public string ie_cancel { get; set; }
        public string pb_id2 { get; set; }
        public string pa_cost { get; set; }
        public string pa_ssno { get; set; }
        public string pa_id2 { get; set; }
    }
}
